### PR TITLE
Updating deps. Adding maintainer

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Awaiting merge of https://github.com/conda-forge/staged-recipes/pull/17629

### CODE REVIEW

**Comment by tdegeus** [comment]
@asottile do you want to be co-maintainer of this ? I ask, because several attempts https://github.com/conda-forge/identify-feedstock/pull/108 , https://github.com/conda-forge/identify-feedstock/pull/107, https://github.com/conda-forge/identify-feedstock/pull/106 , https://github.com/conda-forge/identify-feedstock/pull/105 ) of upgrading got stuck because of a dependency issue, and I think having you here is key to avoid this in the future

**Comment by asottile** [comment]
sure -- can you add `deadsnakes-issues-bot` (my second account)

**Review by nicoddemus — APPROVED** [review]

**Comment by tdegeus** [comment]
@conda-forge-admin, please restart ci

**Comment by tdegeus** [comment]
Good to go!

**Comment by nicoddemus** [comment]
Awesome, thanks!

**Pull request merged**
